### ISSUE TITLE
How can I set a proxy?

### ISSUE THREAD

**Issue by josephearl** [Appdynamics/couchbase-monitoring-extension#5]
Couchbase at my current client is only accessible through a proxy - how can I set this for the Couchbase monitoring extension?

**Comment by venkatakonala** [comment]
Hi Joseph,
Please add the following to the <task-arguments> section in CouchBaseMonitor/monitor.xml .

<argument name="proxy-host" is-required="true" default-value="localhost"/>
<argument name="proxy-port" is-required="true" default-value="8091"/>
<argument name="proxy-username" is-required="true" default-value="Administrator"/>
<argument name="proxy-password" is-required="true" default-value="password"/>

and configure the data. This will set the proxy.
Let me know if you have any other questions.

Thanks and regards,
Venkata Krishna Reddy Konala

**Comment by josephearl** [comment]
Thanks for your help Venkata
